server:
  port: 80
  servlet:
    context-path: /test

spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      address: 127.0.0.1
      port: 9300
      repositories:
        enabled: true

  datasource:
    url: jdbc:mysql://172.24.7.29:3306/financial_cf_dev
    username: root
    password: JRTESTbai!@#123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy=org: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true
